### ISSUE TITLE
cannot import name 'viewer' from 'mujoco'

### ISSUE THREAD

**Issue by yz-cnsdqz** [deepmind/mujoco#626]
Hi all,

I just start to use mujoco by running `pip install mujoco`. After that, I open a python console, and enter `from mujoco import viewer`. However, it pops `cannot import name 'viewer' from 'mujoco' (/xxx/lib/python3.8/site-packages/mujoco/__init__.py)`. 

I have tested some code in the official tutorial [here](https://colab.research.google.com/github/deepmind/mujoco/blob/main/python/tutorial.ipynb#scrollTo=pvh47r97huS4), and it works as expected. So I think the problem just comes from the interactive GUI. 

I am using Ubuntu 20.04, Python3.8, mujoco-2.3.0.

Thanks for help!

**Comment by nimrod-gileadi** [comment]
`viewer` was just added in `mujoco-2.3.1`, which we pushed today. Try it again after upgrading.

**Comment by yz-cnsdqz** [comment]
thanks!

**Comment by saran-t** [comment]
Having said that, I just discovered that `viewer.py` in fact does _not_ work with Python 3.8.. reopening.
